//
//  TemplateDetailViewModel.swift
//  FFmpegRunner
//
//  模板详情 ViewModel
//

import Foundation
import Combine

/// 模板详情 ViewModel
@MainActor
class TemplateDetailViewModel: ObservableObject {

    // MARK: - Published Properties

    /// 当前模板
    @Published var template: Template? {
        didSet {
            if let template = template {
                initializeValues(for: template)
            }
        }
    }

    /// 参数值列表
    @Published var values: [TemplateValue] = []

    /// 验证状态
    @Published private(set) var validationErrors: [String: String] = [:]

    // MARK: - Computed Properties

    /// 参数值字典
    var valuesDictionary: TemplateValueDict {
        values.asDictionary
    }

    /// 是否所有参数都有效
    var isValid: Bool {
        validationErrors.isEmpty && values.allValid
    }

    /// 是否可以执行
    var canExecute: Bool {
        isValid && template != nil
    }

    // MARK: - Private Properties

    // (Removed unused cancellables)
    private var autoGeneratedOutputPaths: [String: String] = [:]

    private static let outputTimestampFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = .current
        formatter.dateFormat = "yyyyMMdd_HHmmss"
        return formatter
    }()
    private static let preferredSourceKeys = ["input", "video", "source", "src", "inputFile", "videoInput"]

    // MARK: - Initialization

    init(template: Template? = nil) {
        self.template = template
        if let template = template {
            initializeValues(for: template)
        }
    }

    // MARK: - Public Methods

    /// 初始化参数值
    func initializeValues(for template: Template) {
        values = TemplateValue.from(template: template)
        validationErrors = [:]
        autoGeneratedOutputPaths.removeAll()
        validateAll()
    }

    /// 更新参数值
    func updateValue(key: String, value: String) {
        guard let index = values.firstIndex(where: { $0.key == key }) else { return }

        values[index].rawValue = value
        validate(key: key)

        trackManualOutputEditIfNeeded(changedKey: key, newValue: value)
        autoFillOutputIfNeeded(changedKey: key)
    }

    /// 获取参数值
    func getValue(for key: String) -> String {
        values.first { $0.key == key }?.rawValue ?? ""
    }

    /// 获取参数定义
    func getParameter(for key: String) -> TemplateParameter? {
        template?.parameters.first { $0.key == key }
    }

    /// 验证单个参数
    func validate(key: String) {
        guard let parameter = getParameter(for: key),
              let index = values.firstIndex(where: { $0.key == key }) else { return }

        let result = parameter.validate(values[index].rawValue)
        values[index].validationResult = result

        if let error = result.errorMessage {
            validationErrors[key] = error
        } else {
            validationErrors.removeValue(forKey: key)
        }
    }

    /// 验证所有参数
    func validateAll() {
        guard let template = template else { return }

        validationErrors = [:]

        for (index, parameter) in template.parameters.enumerated() {
            guard index < values.count else { continue }

            let result = parameter.validate(values[index].rawValue)
            values[index].validationResult = result

            if let error = result.errorMessage {
                validationErrors[parameter.key] = error
            }
        }
    }

    /// 重置为默认值
    func resetToDefaults() {
        guard let template = template else { return }
        initializeValues(for: template)
    }

    // MARK: - Private Helpers

    private func trackManualOutputEditIfNeeded(changedKey: String, newValue: String) {
        guard isOutputParameter(key: changedKey) else { return }

        let trimmed = newValue.trimmingCharacters(in: .whitespacesAndNewlines)

        if trimmed.isEmpty {
            autoGeneratedOutputPaths.removeValue(forKey: changedKey)
            return
        }

        // 用户手动修改输出路径后，不再自动覆盖。
        if let autoGenerated = autoGeneratedOutputPaths[changedKey], trimmed == autoGenerated {
            return
        }

        autoGeneratedOutputPaths.removeValue(forKey: changedKey)
    }

    private func autoFillOutputIfNeeded(changedKey: String) {
        guard let template = template else { return }

        let outputParameters = template.parameters.filter { isOutputParameter($0) }
        guard !outputParameters.isEmpty else { return }

        for outputParameter in outputParameters {
            guard shouldRegenerateOutput(
                outputParameter: outputParameter,
                changedKey: changedKey,
                template: template
            ) else { continue }

            guard let outputIndex = values.firstIndex(where: { $0.key == outputParameter.key }),
                  let sourcePath = sourceFilePath(for: outputParameter, template: template) else { continue }

            let currentOutput = values[outputIndex].rawValue.trimmingCharacters(in: .whitespacesAndNewlines)
            let shouldReplace = currentOutput.isEmpty || currentOutput == autoGeneratedOutputPaths[outputParameter.key]
            guard shouldReplace else { continue }

            let generatedOutput = buildOutputPath(
                fromSourcePath: sourcePath,
                outputParameter: outputParameter,
                template: template
            )
            values[outputIndex].rawValue = generatedOutput
            autoGeneratedOutputPaths[outputParameter.key] = generatedOutput
            validate(key: outputParameter.key)
        }
    }

    private func shouldRegenerateOutput(
        outputParameter: TemplateParameter,
        changedKey: String,
        template: Template
    ) -> Bool {
        if changedKey == outputParameter.key {
            return false
        }

        let sourceKey = sourceKey(for: outputParameter, template: template)

        if changedKey == sourceKey {
            return true
        }

        // 提取音频模板：切换编码器时，应联动调整输出扩展名。
        if template.id == "extract_audio", changedKey == "codec" {
            return true
        }

        return false
    }

    private func sourceFilePath(for outputParameter: TemplateParameter, template: Template) -> String? {
        guard let sourceKey = sourceKey(for: outputParameter, template: template) else { return nil }

        let path = getValue(for: sourceKey).trimmingCharacters(in: .whitespacesAndNewlines)
        guard !path.isEmpty, FileManager.default.fileExists(atPath: path) else { return nil }
        return path
    }

    private func sourceKey(for _: TemplateParameter, template: Template) -> String? {
        let fileInputKeys = template.parameters
            .filter { $0.type == .file && !isOutputParameter($0) }
            .map(\.key)

        guard !fileInputKeys.isEmpty else { return nil }

        for key in Self.preferredSourceKeys where fileInputKeys.contains(key) {
            return key
        }

        return fileInputKeys[0]
    }

    private func isOutputParameter(_ parameter: TemplateParameter) -> Bool {
        parameter.type == .file &&
        (parameter.constraints?.isOutputFile == true || parameter.key == "output")
    }

    private func isOutputParameter(key: String) -> Bool {
        guard let parameter = getParameter(for: key) else { return false }
        return isOutputParameter(parameter)
    }

    private func buildOutputPath(
        fromSourcePath sourcePath: String,
        outputParameter: TemplateParameter,
        template: Template
    ) -> String {
        let sourceURL = URL(fileURLWithPath: sourcePath)
        let directoryURL = sourceURL.deletingLastPathComponent()
        let baseName = sourceURL.deletingPathExtension().lastPathComponent
        let sourceExtension = sourceURL.pathExtension.lowercased()
        let outputExtension = resolveOutputExtension(
            sourceExtension: sourceExtension,
            outputParameter: outputParameter,
            template: template
        )
        let timestamp = Self.outputTimestampFormatter.string(from: Date())

        let outputName: String
        if outputExtension.isEmpty {
            outputName = "\(baseName)_\(timestamp)"
        } else {
            outputName = "\(baseName)_\(timestamp).\(outputExtension)"
        }

        return directoryURL.appendingPathComponent(outputName).path
    }

    private func resolveOutputExtension(
        sourceExtension: String,
        outputParameter: TemplateParameter,
        template: Template
    ) -> String {
        let allowedExtensions = outputParameter.constraints?.fileTypes?.map { $0.lowercased() } ?? []

        if template.id == "extract_audio",
           let codecExtension = extractAudioExtensionByCodec(),
           (allowedExtensions.isEmpty || allowedExtensions.contains(codecExtension)) {
            return codecExtension
        }

        if !allowedExtensions.isEmpty {
            if !sourceExtension.isEmpty, allowedExtensions.contains(sourceExtension) {
                return sourceExtension
            }
            return allowedExtensions[0]
        }

        return sourceExtension
    }

    private func extractAudioExtensionByCodec() -> String? {
        let codec = getValue(for: "codec").trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        switch codec {
        case "libmp3lame":
            return "mp3"
        case "aac":
            return "m4a"
        case "flac":
            return "flac"
        case "pcm_s16le":
            return "wav"
        default:
            return nil
        }
    }

    /// 获取绑定
    func binding(for key: String) -> Binding<String> {
        Binding(
            get: { [weak self] in
                self?.getValue(for: key) ?? ""
            },
            set: { [weak self] newValue in
                self?.updateValue(key: key, value: newValue)
            }
        )
    }
}

// MARK: - Binding Support

import SwiftUI

extension TemplateDetailViewModel {
    /// 创建带验证的 Binding
    func validatedBinding(for key: String) -> Binding<String> {
        Binding(
            get: { [weak self] in
                self?.getValue(for: key) ?? ""
            },
            set: { [weak self] newValue in
                self?.updateValue(key: key, value: newValue)
            }
        )
    }
}
